import PDFDocument from 'pdfkit';
import { prisma } from '../db/prisma';

export interface PdfReportOptions {
  period?: string; // '24h' | '7d' | '30d' | 'all'
  appId?: string;
  userEmail?: string;
}

/**
 * Generates an Executive Security Audit PDF report dynamically from DB analytics
 */
export async function generateExecutivePdfReport(options: PdfReportOptions = {}): Promise<Buffer> {
  const period = options.period || '24h';
  let since = new Date(Date.now() - 24 * 60 * 60 * 1000);
  if (period === '7d') since = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
  else if (period === '30d') since = new Date(Date.now() - 30 * 24 * 60 * 60 * 1000);
  else if (period === 'all') since = new Date(0);

  const whereClause: any = { timestamp: { gte: since } };
  if (options.appId && options.appId !== '*') {
    whereClause.appId = options.appId;
  }

  // Fetch metrics from Prisma DB
  const [
    totalTraffic,
    blockedTraffic,
    allowedTraffic,
    rateLimitedTraffic,
    securityEvents,
    rulesCount,
    exceptionsCount,
    patchesCount,
  ] = await Promise.all([
    prisma.trafficLog.count({ where: whereClause }),
    prisma.trafficLog.count({ where: { ...whereClause, decision: 'BLOCK' } }),
    prisma.trafficLog.count({ where: { ...whereClause, decision: 'ALLOW' } }),
    prisma.trafficLog.count({ where: { ...whereClause, decision: 'RATE_LIMIT' } }),
    prisma.securityEvent.findMany({
      where: whereClause,
      take: 100,
      orderBy: { timestamp: 'desc' },
    }),
    prisma.wafRule.count({ where: { enabled: true } }),
    prisma.wafException.count(),
    prisma.virtualPatch.count({ where: { enabled: true } }),
  ]);

  // Aggregate Category Breakdown
  const categoryMap: Record<string, number> = {};
  const severityMap: Record<string, number> = {};
  const countryMap: Record<string, { count: number; blocked: number }> = {};
  let mlAnomalyCount = 0;

  for (const ev of securityEvents) {
    categoryMap[ev.category] = (categoryMap[ev.category] || 0) + 1;
    severityMap[ev.severity] = (severityMap[ev.severity] || 0) + 1;

    const cName = ev.countryName || 'Unknown';
    if (!countryMap[cName]) countryMap[cName] = { count: 0, blocked: 0 };
    countryMap[cName].count += 1;
    if (ev.decision === 'BLOCK') countryMap[cName].blocked += 1;

    if (ev.mlPrediction === 'ANOMALY' || (ev.mlAnomalyScore && ev.mlAnomalyScore >= 0.6)) {
      mlAnomalyCount += 1;
    }
  }

  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 40, size: 'A4' });
      const buffers: Buffer[] = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', (err) => reject(err));

      // Header Banner
      doc
        .rect(0, 0, 595.28, 80)
        .fill('#0f172a'); // Dark Slate Background

      doc
        .fillColor('#38bdf8')
        .fontSize(22)
        .font('Helvetica-Bold')
        .text('SENTINEL WAF', 40, 20);

      doc
        .fillColor('#94a3b8')
        .fontSize(12)
        .font('Helvetica')
        .text('Executive Security Audit & Threat Intelligence Report', 40, 46);

      // Report Metadata Box
      doc
        .fillColor('#1e293b')
        .rect(40, 95, 515, 60)
        .fill();

      doc
        .fillColor('#f8fafc')
        .fontSize(9)
        .font('Helvetica-Bold')
        .text(`GENERATED ON: ${new Date().toUTCString()}`, 55, 105)
        .text(`REPORTING PERIOD: ${period.toUpperCase()}`, 55, 120)
        .text(`GENERATED BY: ${options.userEmail || 'Sentinel Admin'}`, 55, 135)
        .text(`PROTECTION STATUS: ACTIVE (PREVENTION MODE)`, 300, 105)
        .text(`ACTIVE RULES: ${rulesCount}`, 300, 120)
        .text(`VIRTUAL PATCHES: ${patchesCount} Active`, 300, 135);

      // Section 1: Executive Summary
      doc
        .fillColor('#0f172a')
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('1. EXECUTIVE SUMMARY', 40, 175);

      const blockRate = totalTraffic > 0 ? ((blockedTraffic / totalTraffic) * 100).toFixed(1) : '0.0';

      doc
        .fillColor('#334155')
        .fontSize(10)
        .font('Helvetica')
        .text(
          `During the selected ${period} window, Sentinel WAF processed a total of ${totalTraffic} HTTP/HTTPS requests across protected application boundaries. A total of ${blockedTraffic} malicious or non-compliant requests were mitigated (${blockRate}% block rate).`,
          40,
          195,
          { width: 515 }
        );

      // Metric Cards Grid
      const drawCard = (x: number, y: number, label: string, val: string, color: string) => {
        doc.rect(x, y, 120, 50).fillAndStroke('#f8fafc', '#e2e8f0');
        doc.fillColor('#64748b').fontSize(8).font('Helvetica-Bold').text(label.toUpperCase(), x + 8, y + 8);
        doc.fillColor(color).fontSize(16).font('Helvetica-Bold').text(val, x + 8, y + 22);
      };

      drawCard(40, 240, 'Total Traffic', String(totalTraffic), '#0f172a');
      drawCard(170, 240, 'Blocked Requests', String(blockedTraffic), '#ef4444');
      drawCard(300, 240, 'Allowed Traffic', String(allowedTraffic), '#22c55e');
      drawCard(435, 240, 'Rate Limited', String(rateLimitedTraffic), '#f59e0b');

      // Section 2: Attack Categories & Threat Severity
      doc
        .fillColor('#0f172a')
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('2. ATTACK VECTOR & SEVERITY DISTRIBUTION', 40, 310);

      doc.fontSize(9).font('Helvetica-Bold').fillColor('#475569');
      doc.text('CATEGORY', 40, 335);
      doc.text('EVENTS DETECTED', 200, 335);
      doc.text('SEVERITY OVERVIEW', 350, 335);

      doc.moveTo(40, 348).lineTo(555, 348).stroke('#cbd5e1');

      let curY = 355;
      const categories = Object.keys(categoryMap);
      if (categories.length === 0) {
        doc.fillColor('#64748b').fontSize(9).font('Helvetica-Oblique').text('No security threats or attack vectors detected during this reporting window.', 40, curY);
        curY += 20;
      } else {
        for (const cat of categories.slice(0, 5)) {
          doc.fillColor('#1e293b').fontSize(9).font('Helvetica-Bold').text(cat, 40, curY);
          doc.fillColor('#334155').fontSize(9).font('Helvetica').text(String(categoryMap[cat]), 200, curY);
          doc.fillColor('#dc2626').fontSize(9).font('Helvetica').text(severityMap['CRITICAL'] ? 'HIGH/CRITICAL IMPACT' : 'MEDIUM IMPACT', 350, curY);
          curY += 18;
        }
      }

      // Section 3: GeoIP Threat Intelligence & Top Countries
      doc
        .fillColor('#0f172a')
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('3. GEOGRAPHIC THREAT ORIGIN SUMMARY', 40, curY + 20);

      curY += 45;
      doc.fontSize(9).font('Helvetica-Bold').fillColor('#475569');
      doc.text('COUNTRY ORIGIN', 40, curY);
      doc.text('ATTACK EVENTS', 220, curY);
      doc.text('BLOCKED COUNT', 370, curY);

      doc.moveTo(40, curY + 13).lineTo(555, curY + 13).stroke('#cbd5e1');
      curY += 20;

      const countries = Object.keys(countryMap);
      if (countries.length === 0) {
        doc.fillColor('#64748b').fontSize(9).font('Helvetica-Oblique').text('No geographic attack origins recorded in this period.', 40, curY);
        curY += 20;
      } else {
        for (const cName of countries.slice(0, 5)) {
          doc.fillColor('#1e293b').fontSize(9).font('Helvetica').text(cName, 40, curY);
          doc.fillColor('#334155').fontSize(9).font('Helvetica').text(String(countryMap[cName].count), 220, curY);
          doc.fillColor('#ef4444').fontSize(9).font('Helvetica-Bold').text(String(countryMap[cName].blocked), 370, curY);
          curY += 18;
        }
      }

      // Section 4: Machine Learning Anomaly Detection (Shadow Mode)
      doc
        .fillColor('#0f172a')
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('4. MACHINE-LEARNING ANOMALY DETECTION (SHADOW MODE)', 40, curY + 20);

      curY += 45;
      doc
        .fillColor('#334155')
        .fontSize(9)
        .font('Helvetica')
        .text(
          `Sentinel ML HTTP Anomaly Scorer (v1.2) evaluated requests in non-blocking shadow mode. ${mlAnomalyCount} requests exhibited statistical structural anomalies (score >= 0.60). Authoritative WAF policy remained deterministic.`,
          40,
          curY,
          { width: 515 }
        );

      curY += 35;

      // Section 5: Virtual Patching & Active Exceptions
      doc
        .fillColor('#0f172a')
        .fontSize(14)
        .font('Helvetica-Bold')
        .text('5. VIRTUAL PATCHES & FALSE-POSITIVE EXCEPTIONS', 40, curY);

      curY += 25;
      doc
        .fillColor('#334155')
        .fontSize(9)
        .font('Helvetica')
        .text(`Active Virtual Patches: ${patchesCount} rule(s) protecting unpatched application vulnerabilities.`, 40, curY);
      doc
        .text(`Active Bypasses / False-Positive Exceptions: ${exceptionsCount} scoped, expiring exceptions currently active.`, 40, curY + 15);

      // Footer
      doc
        .fillColor('#94a3b8')
        .fontSize(8)
        .font('Helvetica-Oblique')
        .text('Confidential - Sentinel Web Application Firewall Enterprise Report - Generated for Internal Audit Only', 40, 770, { align: 'center' });

      doc.end();
    } catch (err) {
      reject(err);
    }
  });
}
